export const CREATE_TECH = 'CREATE_TECH';
export const LOAD_TECH_SUCCESS = 'LOAD_TECH_SUCCESS';
export const CREATE_TECH_SUCCESS = 'CREATE_TECH_SUCCESS';
export const UPDATE_TECH_SUCCESS = 'UPDATE_TECH_SUCCESS';
export const BEFORE_API_CALL = 'BEFORE_API_CALL';